version: '3.9'

services:

  redis:
    image: redis
    hostname: redis
    ports:
     - "6379:6379"
    healthcheck:
      test: exit 0

  users-service-db:
    image: chapter04-users-service-db
    #build: ./UsersService/db
    volumes:
      - pgdata:/var/lib/postgresql/data
    hostname: users-service-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: exit 0

  userservice:
    image: chapter04-userservice
    #build: ./UsersService
    ports:
      - 8080:3000
    environment:
      - APP_RD_ADDRESS=redis:6379
      - APP_RD_AUTH=password
      - APP_RD_DBNAME=0
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-service-db:5432/users_prod?sslmode=disable
      - DATABASE_DEV_URL=postgres://postgres:postgres@users-service-db:5432/users_dev?sslmode=disable
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-service-db:5432/users_test?sslmode=disable
    depends_on:
      - users-service-db
      - redis
volumes:
  pgdata: